# Generated by Django 5.0.14 on 2026-03-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_location', models.CharField(max_length=100)),
                ('accommodation_preference', models.CharField(blank=True, choices=[('budget', 'Budget'), ('standard', 'Standard'), ('luxury', 'Luxury')], max_length=50, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('heard_about_us', models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('friend', 'Friend'), ('blog', 'Travel Blog'), ('other', 'Other')], max_length=20, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
